name: qwietaifix

on:
  pull_request:
  workflow_dispatch:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Set up Java JDK v11
    - name: Setup Java JDK v11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11

    # Set up C++ environment (g++ and related tools)
    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ clang++ cmake

    # Install Conan
    - name: Install Conan
      run: |
        pip install conan
        conan profile detect

    # Install vcpkg
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        echo "VCPKG_ROOT=$GITHUB_WORKSPACE/vcpkg" >> $GITHUB_ENV

    # Generate conanfile.txt from vcpkg
    - name: Generate conanfile.txt from vcpkg
      run: |
        echo "[requires]" > conanfile.txt
        ./vcpkg/vcpkg list | grep -v "fmt" | awk '{print $1"/latest"}' >> conanfile.txt
        # Explicitly add fmt with the required version
        echo "fmt/10.1.1" >> conanfile.txt
        echo -e "\n[generators]\nCMakeDeps\nCMakeToolchain" >> conanfile.txt

    # Run Conan Install with vcpkg dependencies
    - name: Run Conan Install with vcpkg dependencies
      run: |
        conan install . --build=missing --output-folder=conan_build

    # Install compiledb
    - name: Install compiledb
      run: |
        pip install compiledb

    # Generate Compilation Database using Make and compiledb
    - name: Generate Compilation Database using Make and compiledb
      run: |
        compiledb make

    # Configure CMake with Makefiles
    - name: Configure CMake with Makefiles
      run: |
        cmake -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM=/usr/bin/make ..

    # Download ShiftLeft CLI
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    # Run preZero Static Analysis
    - name: preZero Static Analysis
      run: |
        ${GITHUB_WORKSPACE}/sl --version
        ${GITHUB_WORKSPACE}/sl analyze --strict --wait --verbose \
          --app C-test-App \
          --tag branch=${{ github.head_ref }} --c .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_HOST: www.shiftleft.io
        SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
        SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443
